/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TooltipIndexRouteImport } from './routes/tooltip/index'
import { Route as TextPageIndexRouteImport } from './routes/text-page/index'
import { Route as TextFieldIndexRouteImport } from './routes/text-field/index'
import { Route as TextAreaIndexRouteImport } from './routes/text-area/index'
import { Route as TagGroupIndexRouteImport } from './routes/tag-group/index'
import { Route as SwitchIndexRouteImport } from './routes/switch/index'
import { Route as SelectIndexRouteImport } from './routes/select/index'
import { Route as RadioGroupIndexRouteImport } from './routes/radio-group/index'
import { Route as ModalDialogIndexRouteImport } from './routes/modal-dialog/index'
import { Route as InlineAlertIndexRouteImport } from './routes/inline-alert/index'
import { Route as CheckboxGroupIndexRouteImport } from './routes/checkbox-group/index'
import { Route as CalloutIndexRouteImport } from './routes/callout/index'
import { Route as ButtonIndexRouteImport } from './routes/button/index'
import { Route as ButtonGroupIndexRouteImport } from './routes/button-group/index'
import { Route as AlertBannerIndexRouteImport } from './routes/alert-banner/index'
import { Route as AccordionGroupIndexRouteImport } from './routes/accordion-group/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TooltipIndexRoute = TooltipIndexRouteImport.update({
  id: '/tooltip/',
  path: '/tooltip/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextPageIndexRoute = TextPageIndexRouteImport.update({
  id: '/text-page/',
  path: '/text-page/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextFieldIndexRoute = TextFieldIndexRouteImport.update({
  id: '/text-field/',
  path: '/text-field/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextAreaIndexRoute = TextAreaIndexRouteImport.update({
  id: '/text-area/',
  path: '/text-area/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagGroupIndexRoute = TagGroupIndexRouteImport.update({
  id: '/tag-group/',
  path: '/tag-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchIndexRoute = SwitchIndexRouteImport.update({
  id: '/switch/',
  path: '/switch/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectIndexRoute = SelectIndexRouteImport.update({
  id: '/select/',
  path: '/select/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioGroupIndexRoute = RadioGroupIndexRouteImport.update({
  id: '/radio-group/',
  path: '/radio-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalDialogIndexRoute = ModalDialogIndexRouteImport.update({
  id: '/modal-dialog/',
  path: '/modal-dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const InlineAlertIndexRoute = InlineAlertIndexRouteImport.update({
  id: '/inline-alert/',
  path: '/inline-alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxGroupIndexRoute = CheckboxGroupIndexRouteImport.update({
  id: '/checkbox-group/',
  path: '/checkbox-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalloutIndexRoute = CalloutIndexRouteImport.update({
  id: '/callout/',
  path: '/callout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonIndexRoute = ButtonIndexRouteImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonGroupIndexRoute = ButtonGroupIndexRouteImport.update({
  id: '/button-group/',
  path: '/button-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertBannerIndexRoute = AlertBannerIndexRouteImport.update({
  id: '/alert-banner/',
  path: '/alert-banner/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionGroupIndexRoute = AccordionGroupIndexRouteImport.update({
  id: '/accordion-group/',
  path: '/accordion-group/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion-group': typeof AccordionGroupIndexRoute
  '/alert-banner': typeof AlertBannerIndexRoute
  '/button-group': typeof ButtonGroupIndexRoute
  '/button': typeof ButtonIndexRoute
  '/callout': typeof CalloutIndexRoute
  '/checkbox-group': typeof CheckboxGroupIndexRoute
  '/inline-alert': typeof InlineAlertIndexRoute
  '/modal-dialog': typeof ModalDialogIndexRoute
  '/radio-group': typeof RadioGroupIndexRoute
  '/select': typeof SelectIndexRoute
  '/switch': typeof SwitchIndexRoute
  '/tag-group': typeof TagGroupIndexRoute
  '/text-area': typeof TextAreaIndexRoute
  '/text-field': typeof TextFieldIndexRoute
  '/text-page': typeof TextPageIndexRoute
  '/tooltip': typeof TooltipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion-group': typeof AccordionGroupIndexRoute
  '/alert-banner': typeof AlertBannerIndexRoute
  '/button-group': typeof ButtonGroupIndexRoute
  '/button': typeof ButtonIndexRoute
  '/callout': typeof CalloutIndexRoute
  '/checkbox-group': typeof CheckboxGroupIndexRoute
  '/inline-alert': typeof InlineAlertIndexRoute
  '/modal-dialog': typeof ModalDialogIndexRoute
  '/radio-group': typeof RadioGroupIndexRoute
  '/select': typeof SelectIndexRoute
  '/switch': typeof SwitchIndexRoute
  '/tag-group': typeof TagGroupIndexRoute
  '/text-area': typeof TextAreaIndexRoute
  '/text-field': typeof TextFieldIndexRoute
  '/text-page': typeof TextPageIndexRoute
  '/tooltip': typeof TooltipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion-group/': typeof AccordionGroupIndexRoute
  '/alert-banner/': typeof AlertBannerIndexRoute
  '/button-group/': typeof ButtonGroupIndexRoute
  '/button/': typeof ButtonIndexRoute
  '/callout/': typeof CalloutIndexRoute
  '/checkbox-group/': typeof CheckboxGroupIndexRoute
  '/inline-alert/': typeof InlineAlertIndexRoute
  '/modal-dialog/': typeof ModalDialogIndexRoute
  '/radio-group/': typeof RadioGroupIndexRoute
  '/select/': typeof SelectIndexRoute
  '/switch/': typeof SwitchIndexRoute
  '/tag-group/': typeof TagGroupIndexRoute
  '/text-area/': typeof TextAreaIndexRoute
  '/text-field/': typeof TextFieldIndexRoute
  '/text-page/': typeof TextPageIndexRoute
  '/tooltip/': typeof TooltipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion-group'
    | '/alert-banner'
    | '/button-group'
    | '/button'
    | '/callout'
    | '/checkbox-group'
    | '/inline-alert'
    | '/modal-dialog'
    | '/radio-group'
    | '/select'
    | '/switch'
    | '/tag-group'
    | '/text-area'
    | '/text-field'
    | '/text-page'
    | '/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion-group'
    | '/alert-banner'
    | '/button-group'
    | '/button'
    | '/callout'
    | '/checkbox-group'
    | '/inline-alert'
    | '/modal-dialog'
    | '/radio-group'
    | '/select'
    | '/switch'
    | '/tag-group'
    | '/text-area'
    | '/text-field'
    | '/text-page'
    | '/tooltip'
  id:
    | '__root__'
    | '/'
    | '/accordion-group/'
    | '/alert-banner/'
    | '/button-group/'
    | '/button/'
    | '/callout/'
    | '/checkbox-group/'
    | '/inline-alert/'
    | '/modal-dialog/'
    | '/radio-group/'
    | '/select/'
    | '/switch/'
    | '/tag-group/'
    | '/text-area/'
    | '/text-field/'
    | '/text-page/'
    | '/tooltip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionGroupIndexRoute: typeof AccordionGroupIndexRoute
  AlertBannerIndexRoute: typeof AlertBannerIndexRoute
  ButtonGroupIndexRoute: typeof ButtonGroupIndexRoute
  ButtonIndexRoute: typeof ButtonIndexRoute
  CalloutIndexRoute: typeof CalloutIndexRoute
  CheckboxGroupIndexRoute: typeof CheckboxGroupIndexRoute
  InlineAlertIndexRoute: typeof InlineAlertIndexRoute
  ModalDialogIndexRoute: typeof ModalDialogIndexRoute
  RadioGroupIndexRoute: typeof RadioGroupIndexRoute
  SelectIndexRoute: typeof SelectIndexRoute
  SwitchIndexRoute: typeof SwitchIndexRoute
  TagGroupIndexRoute: typeof TagGroupIndexRoute
  TextAreaIndexRoute: typeof TextAreaIndexRoute
  TextFieldIndexRoute: typeof TextFieldIndexRoute
  TextPageIndexRoute: typeof TextPageIndexRoute
  TooltipIndexRoute: typeof TooltipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooltip/': {
      id: '/tooltip/'
      path: '/tooltip'
      fullPath: '/tooltip'
      preLoaderRoute: typeof TooltipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-page/': {
      id: '/text-page/'
      path: '/text-page'
      fullPath: '/text-page'
      preLoaderRoute: typeof TextPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-field/': {
      id: '/text-field/'
      path: '/text-field'
      fullPath: '/text-field'
      preLoaderRoute: typeof TextFieldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-area/': {
      id: '/text-area/'
      path: '/text-area'
      fullPath: '/text-area'
      preLoaderRoute: typeof TextAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-group/': {
      id: '/tag-group/'
      path: '/tag-group'
      fullPath: '/tag-group'
      preLoaderRoute: typeof TagGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch/': {
      id: '/switch/'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select/': {
      id: '/select/'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio-group/': {
      id: '/radio-group/'
      path: '/radio-group'
      fullPath: '/radio-group'
      preLoaderRoute: typeof RadioGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal-dialog/': {
      id: '/modal-dialog/'
      path: '/modal-dialog'
      fullPath: '/modal-dialog'
      preLoaderRoute: typeof ModalDialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inline-alert/': {
      id: '/inline-alert/'
      path: '/inline-alert'
      fullPath: '/inline-alert'
      preLoaderRoute: typeof InlineAlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox-group/': {
      id: '/checkbox-group/'
      path: '/checkbox-group'
      fullPath: '/checkbox-group'
      preLoaderRoute: typeof CheckboxGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callout/': {
      id: '/callout/'
      path: '/callout'
      fullPath: '/callout'
      preLoaderRoute: typeof CalloutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button/': {
      id: '/button/'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-group/': {
      id: '/button-group/'
      path: '/button-group'
      fullPath: '/button-group'
      preLoaderRoute: typeof ButtonGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-banner/': {
      id: '/alert-banner/'
      path: '/alert-banner'
      fullPath: '/alert-banner'
      preLoaderRoute: typeof AlertBannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion-group/': {
      id: '/accordion-group/'
      path: '/accordion-group'
      fullPath: '/accordion-group'
      preLoaderRoute: typeof AccordionGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionGroupIndexRoute: AccordionGroupIndexRoute,
  AlertBannerIndexRoute: AlertBannerIndexRoute,
  ButtonGroupIndexRoute: ButtonGroupIndexRoute,
  ButtonIndexRoute: ButtonIndexRoute,
  CalloutIndexRoute: CalloutIndexRoute,
  CheckboxGroupIndexRoute: CheckboxGroupIndexRoute,
  InlineAlertIndexRoute: InlineAlertIndexRoute,
  ModalDialogIndexRoute: ModalDialogIndexRoute,
  RadioGroupIndexRoute: RadioGroupIndexRoute,
  SelectIndexRoute: SelectIndexRoute,
  SwitchIndexRoute: SwitchIndexRoute,
  TagGroupIndexRoute: TagGroupIndexRoute,
  TextAreaIndexRoute: TextAreaIndexRoute,
  TextFieldIndexRoute: TextFieldIndexRoute,
  TextPageIndexRoute: TextPageIndexRoute,
  TooltipIndexRoute: TooltipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
